### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by Exlord** [danrossi/mediastream-tech#1]
Hi, I am trying to use this but its not working , all I am getting is `VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.`

It seems that this is not getting registered! 
I am on `vue3` + `ts` ..

Have tested this?

**Comment by danrossi** [comment]
vue is overcomplicated with a bad webpack bundle system. I've not been successful importing some of my features that are not source code and requires some self loading like normal includes. They have to be added to the head as script includes and somehow reference videojs globally. 

I've added the videojs import required or else its treated as global / window. When importing videojs into vue its not added to global.
